#!/usr/bin/env bash

# Exportamos los valores como variables globales, para que no nos pida datos al conectar
export BORG_REPO='borg@SRV_VAR:DIR_VAR'
export BORG_PASSPHRASE='PASS_VAR'

# some helpers and error handling:
info() { printf "\n%s %s\n\n" "$( date )" "$*" >&2; }
trap 'echo $( date ) Backup interrupted >&2; exit 2' INT TERM

info "Comenzando backup"

# Configurar directorios para hacer backups, exclusiones y compresion

borg create                         \
    --verbose                       \
    --filter AME                    \
    --list                          \
    --stats                         \
    --show-rc                       \
    --compression lz4               \
    --exclude-caches                \
    --exclude '/home/*/.cache/*'    \
    --exclude '/var/cache/*'        \
    --exclude '/var/tmp/*'          \
                                    \
    ::'{hostname}-{now}'            \
    /etc                            \
    /home                           \
    /root                           \
    /var                            \
    /u                              \

backup_exit=$?

if [ ${backup_exit} -eq 1 ];
then
    info "Backup completado con advertencias"
fi

if [ ${backup_exit} -gt 1 ];
then
    info "Backup completado con error"
fi

exit ${backup_exit}
